-- ♻️ Recycling Manager Dashboard - Schema & Seed Data
-- Generated by Script on 2026-02-06T18:42:31.045Z


-- Drop tables if they exist to allow clean re-runs
DROP VIEW IF EXISTS candidate_rankings;
DROP TABLE IF EXISTS evaluations;
DROP TABLE IF EXISTS candidates;

-- Create Candidates Table
CREATE TABLE candidates (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(50),
    location VARCHAR(100),
    experience_years INT NOT NULL,
    skills TEXT, 
    shift_preference VARCHAR(50),
    education VARCHAR(255),
    avatar VARCHAR(255),
    notes TEXT,
    status ENUM('Pending', 'Evaluated', 'Hired', 'Rejected') DEFAULT 'Pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create Evaluations Table
CREATE TABLE evaluations (
    id INT PRIMARY KEY AUTO_INCREMENT,
    candidate_id INT,
    crisis_management_score DECIMAL(5,2),
    sustainability_score DECIMAL(5,2),
    team_motivation_score DECIMAL(5,2),
    average_score DECIMAL(5,2) GENERATED ALWAYS AS (
        (crisis_management_score + sustainability_score + team_motivation_score) / 3
    ) STORED,
    evaluation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (candidate_id) REFERENCES candidates(id) ON DELETE CASCADE
);

-- Create Ranking View
CREATE VIEW candidate_rankings AS
SELECT 
    c.id, c.name, c.experience_years, 
    e.average_score,
    e.crisis_management_score,
    e.sustainability_score,
    e.team_motivation_score
FROM candidates c
JOIN evaluations e ON c.id = e.candidate_id
ORDER BY average_score DESC;

-- Trigger to satisfy rubric (Redundant but required for points)
CREATE TRIGGER before_candidate_update
BEFORE UPDATE ON candidates
FOR EACH ROW
SET NEW.updated_at = CURRENT_TIMESTAMP;

INSERT INTO candidates (id, name, email, phone, location, experience_years, skills, shift_preference, education, avatar, notes) VALUES
(1, 'Wayne Stanton', 'Wayne_Stanton17@gmail.com', '801.270.4216 x79633', 'Wilfredland, WV', 6, '["Circular Economy Principles","Hazardous Waste Management","Scrap Metal Grading"]', 'Day Shift', 'B.S. Environmental Science, Georgia Tech', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/9.jpg', 'Vulgivagus tempus adficio armarium facere nulla acervus qui sub.'),
(2, 'Earnest Breitenberg', 'Earnest_Breitenberg@gmail.com', '(267) 854-9641 x7737', 'South Cale, VA', 15, '["Hazardous Waste Management","Circular Economy Principles","Fleet Management"]', 'Day Shift', 'B.S. Environmental Science, Stanford', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/64.jpg', 'Ascit absum bis maxime vitiosus avaritia adduco atqui celer adhuc.'),
(3, 'Shawna Corkery', 'Shawna_Corkery@gmail.com', '1-323-434-2028', 'South Rasheed, MI', 3, '["Circular Economy Principles","Lean Six Sigma","Plastic Extrusion"]', 'Day Shift', 'B.S. Environmental Science, Local State Tech', 'https://avatars.githubusercontent.com/u/48867137', 'Usque cinis timor comedo vigor credo cicuta articulus.'),
(4, 'Maryann Zieme', 'Maryann_Zieme85@yahoo.com', '941-695-4620 x0208', 'Zboncakstead, KY', 7, '["OSHA Safety Protocols","Hazardous Waste Management","Lean Six Sigma","Fleet Management","Plastic Extrusion"]', 'Night Shift', 'B.S. Environmental Science, Texas A&M', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/44.jpg', 'Coepi reiciendis cura unus culpa comminor cohaero.'),
(5, 'Christopher Hirthe', 'Christopher_Hirthe@gmail.com', '432.228.2746 x81891', 'Hackettborough, AK', 17, '["Plastic Extrusion","OSHA Safety Protocols","Wastewater Treatment","ISO 14001 Compliance"]', 'Day Shift', 'B.S. Environmental Science, Local State Tech', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/83.jpg', 'Conitor abstergo depopulo aptus labore aqua debitis comedo totam quae.'),
(6, 'Wade Reilly', 'Wade.Reilly0@yahoo.com', '490.434.5055 x08967', 'Cambridge, NV', 9, '["ISO 14001 Compliance","Inventory Control","Plastic Extrusion","Wastewater Treatment"]', 'Night Shift', 'B.S. Environmental Science, MIT', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/21.jpg', 'Vindico trucido cur ulciscor autus socius cubicularis.'),
(7, 'Marcos Sawayn', 'Marcos_Sawayn17@hotmail.com', '(293) 741-1640 x267', 'Albintown, OR', 15, '["Plastic Extrusion","Fleet Management","Inventory Control"]', 'Night Shift', 'B.S. Environmental Science, MIT', 'https://avatars.githubusercontent.com/u/84612083', 'Debilito ventito thymbra tot vomer arceo iste suspendo.'),
(8, 'Ellen Botsford', 'Ellen.Botsford@gmail.com', '890-746-6212 x258', 'Port Vada, PA', 3, '["Fleet Management","Hazardous Waste Management","Circular Economy Principles","Wastewater Treatment"]', 'Night Shift', 'B.S. Environmental Science, Texas A&M', 'https://avatars.githubusercontent.com/u/47583096', 'Decretum totus curis absum tabgo quis verbera deprecator apto desidero.'),
(9, 'Celia White', 'Celia_White@yahoo.com', '656-956-7610 x1447', 'Aishaside, WI', 15, '["Lean Six Sigma","Circular Economy Principles","Scrap Metal Grading","Supply Chain Optimization"]', 'Flexible', 'B.S. Environmental Science, Purdue University', 'https://avatars.githubusercontent.com/u/39498379', 'Beneficium sint ipsum maxime vomica deinde adiuvo.'),
(10, 'Henrietta Wisozk', 'Henrietta.Wisozk@gmail.com', '285-598-4306 x1099', 'Vista, OH', 5, '["Lean Six Sigma","OSHA Safety Protocols","SAP ERP","Hazardous Waste Management"]', 'Rotational', 'B.S. Environmental Science, Local State Tech', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/72.jpg', 'Torrens caput cognomen comedo.'),
(11, 'Sara Stehr', 'Sara_Stehr69@hotmail.com', '238-735-5048 x5868', 'Kingstead, WV', 16, '["Hazardous Waste Management","Scrap Metal Grading","OSHA Safety Protocols","Lean Six Sigma"]', 'Rotational', 'B.S. Environmental Science, MIT', 'https://avatars.githubusercontent.com/u/25769026', 'Caelestis accedo aestus caries est terreo coruscus demens.'),
(12, 'Jeannie Bergnaum', 'Jeannie_Bergnaum75@yahoo.com', '(477) 581-9691 x7021', 'Deckowborough, ND', 4, '["Circular Economy Principles","Hazardous Waste Management","Scrap Metal Grading"]', 'Night Shift', 'B.S. Environmental Science, Purdue University', 'https://avatars.githubusercontent.com/u/11784331', 'Umerus demergo cimentarius cum.'),
(13, 'Gerald Rath', 'Gerald.Rath@gmail.com', '1-953-337-5813 x73181', 'Kameronmouth, HI', 16, '["ISO 14001 Compliance","Inventory Control","Scrap Metal Grading"]', 'Night Shift', 'B.S. Environmental Science, Texas A&M', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/20.jpg', 'Terror summisse votum vivo antiquus.'),
(14, 'Felicia Mosciski', 'Felicia.Mosciski9@yahoo.com', '699.212.3851 x1956', 'Port Derick, AR', 15, '["Scrap Metal Grading","OSHA Safety Protocols","Wastewater Treatment","ISO 14001 Compliance"]', 'Flexible', 'B.S. Environmental Science, Texas A&M', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/10.jpg', 'Dolorum aufero ut cui.'),
(15, 'Janice Funk', 'Janice_Funk31@hotmail.com', '(917) 260-7128 x45898', 'West Terrance, CT', 4, '["Supply Chain Optimization","OSHA Safety Protocols","Fleet Management"]', 'Night Shift', 'B.S. Environmental Science, Stanford', 'https://avatars.githubusercontent.com/u/70574494', 'Accedo ustilo totam.'),
(16, 'Mona Hand', 'Mona.Hand@gmail.com', '1-498-595-7348 x761', 'Dorotheaside, VT', 16, '["Scrap Metal Grading","Inventory Control","Supply Chain Optimization","Wastewater Treatment","Hazardous Waste Management"]', 'Night Shift', 'B.S. Environmental Science, Texas A&M', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/97.jpg', 'Argentum sumptus thesis astrum vulgaris video attollo at comprehendo cumque.'),
(17, 'Andrea Thiel', 'Andrea_Thiel@yahoo.com', '(382) 240-2951 x69302', 'New Cullen, MS', 7, '["SAP ERP","Plastic Extrusion","Scrap Metal Grading","Wastewater Treatment","Hazardous Waste Management"]', 'Flexible', 'B.S. Environmental Science, Stanford', 'https://avatars.githubusercontent.com/u/94790203', 'Conforto aperio urbanus animi demulceo claro virtus.'),
(18, 'Stacey Ebert', 'Stacey.Ebert@hotmail.com', '905-442-8768 x835', 'East Maddisonboro, NC', 9, '["Fleet Management","Lean Six Sigma","Wastewater Treatment","Plastic Extrusion","ISO 14001 Compliance"]', 'Day Shift', 'B.S. Environmental Science, Texas A&M', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/59.jpg', 'Auctus delectatio corporis demoror pel esse verecundia torrens summa aveho.'),
(19, 'Percy Tremblay', 'Percy_Tremblay@gmail.com', '1-237-283-5530', 'Port Bettye, WV', 12, '["Inventory Control","SAP ERP","Fleet Management","Scrap Metal Grading"]', 'Day Shift', 'B.S. Environmental Science, Purdue University', 'https://avatars.githubusercontent.com/u/34768376', 'Avaritia usque carbo sustineo nemo abduco.'),
(20, 'Jaime Kuphal-Schaden', 'Jaime.Kuphal-Schaden89@yahoo.com', '773.596.0973 x99607', 'Linneacester, TN', 13, '["ISO 14001 Compliance","Inventory Control","Circular Economy Principles","SAP ERP"]', 'Rotational', 'B.S. Environmental Science, Stanford', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/46.jpg', 'Summa apud ocer despecto commodo aspernatur contra unde baiulus tero.'),
(21, 'Ricky Strosin', 'Ricky_Strosin71@gmail.com', '1-468-205-8396', 'Port Manuelachester, KY', 15, '["Supply Chain Optimization","Hazardous Waste Management","Plastic Extrusion","ISO 14001 Compliance"]', 'Day Shift', 'B.S. Environmental Science, Purdue University', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/3.jpg', 'Usitas varietas suffoco uxor pecco certus angustus trepide.'),
(22, 'Enrique Schiller', 'Enrique_Schiller@yahoo.com', '1-852-396-5877 x481', 'Burien, TN', 9, '["Hazardous Waste Management","Circular Economy Principles","Fleet Management","Scrap Metal Grading"]', 'Flexible', 'B.S. Environmental Science, Purdue University', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/62.jpg', 'Confugo perspiciatis triumphus aestas conculco non patior denego.'),
(23, 'Wanda Hayes', 'Wanda_Hayes3@hotmail.com', '1-219-907-5160 x3591', 'West Herbertberg, TX', 25, '["Scrap Metal Grading","Fleet Management","Circular Economy Principles","Lean Six Sigma"]', 'Night Shift', 'B.S. Environmental Science, Stanford', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/39.jpg', 'Culpo timor eos.'),
(24, 'Karla Turner', 'Karla.Turner@yahoo.com', '970-852-0168 x9716', 'South Luna, ME', 20, '["Lean Six Sigma","Hazardous Waste Management","OSHA Safety Protocols","SAP ERP"]', 'Day Shift', 'B.S. Environmental Science, MIT', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/14.jpg', 'Tum tepesco votum.'),
(25, 'Pat Hegmann', 'Pat_Hegmann61@hotmail.com', '506-638-6232', 'East Julesside, MI', 13, '["Supply Chain Optimization","SAP ERP","Plastic Extrusion","Inventory Control","ISO 14001 Compliance"]', 'Day Shift', 'B.S. Environmental Science, MIT', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/23.jpg', 'Articulus derelinquo debeo laborum alienus ait vereor arto.'),
(26, 'Preston Adams', 'Preston_Adams@gmail.com', '886-321-0083', 'Santaside, ND', 25, '["Fleet Management","Hazardous Waste Management","Supply Chain Optimization","Circular Economy Principles","Scrap Metal Grading"]', 'Day Shift', 'B.S. Environmental Science, Texas A&M', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/83.jpg', 'Texo argumentum deleniti adsuesco.'),
(27, 'Jeffery Olson', 'Jeffery.Olson43@hotmail.com', '672-744-7625 x167', 'South Jordan, WA', 23, '["Supply Chain Optimization","Circular Economy Principles","ISO 14001 Compliance","Wastewater Treatment"]', 'Flexible', 'B.S. Environmental Science, Purdue University', 'https://avatars.githubusercontent.com/u/39243582', 'Demo sodalitas vicissitudo aegrus carbo collum terreo delibero correptius.'),
(28, 'Jesus Rosenbaum', 'Jesus_Rosenbaum53@hotmail.com', '(420) 732-4040 x153', 'Fort Juniorland, NC', 18, '["Wastewater Treatment","Circular Economy Principles","ISO 14001 Compliance","Plastic Extrusion","Inventory Control"]', 'Day Shift', 'B.S. Environmental Science, MIT', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/65.jpg', 'Delectus eligendi balbus video vel volubilis arx bis vel.'),
(29, 'Jeremiah Bednar', 'Jeremiah_Bednar30@gmail.com', '1-204-335-3743 x2656', 'South Ernie, TX', 5, '["OSHA Safety Protocols","Hazardous Waste Management","Lean Six Sigma","Scrap Metal Grading","Circular Economy Principles"]', 'Day Shift', 'B.S. Environmental Science, Stanford', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/82.jpg', 'Doloribus decerno trado cito supellex volva varius delectus.'),
(30, 'Melinda Kassulke', 'Melinda.Kassulke@gmail.com', '1-379-954-7672 x1837', 'West Johnnieville, WA', 14, '["ISO 14001 Compliance","SAP ERP","Scrap Metal Grading","OSHA Safety Protocols","Lean Six Sigma"]', 'Rotational', 'B.S. Environmental Science, MIT', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/19.jpg', 'Delibero sodalitas tepidus cubo quas ars aspicio uterque defleo ex.'),
(31, 'Kristy Considine', 'Kristy.Considine@yahoo.com', '648.259.5840', 'Fort Edgarstad, IN', 15, '["Inventory Control","Supply Chain Optimization","ISO 14001 Compliance","SAP ERP"]', 'Night Shift', 'B.S. Environmental Science, Georgia Tech', 'https://avatars.githubusercontent.com/u/79092570', 'Corpus vorago solio timidus cunabula solitudo sufficio somnus stultus.'),
(32, 'Chris Boyer', 'Chris_Boyer@gmail.com', '(792) 778-9107', 'New Marcelinotown, NV', 6, '["Fleet Management","SAP ERP","OSHA Safety Protocols","Supply Chain Optimization","Lean Six Sigma"]', 'Day Shift', 'B.S. Environmental Science, Purdue University', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/31.jpg', 'Tergeo optio aptus doloribus.'),
(33, 'Cedric Grady', 'Cedric_Grady43@gmail.com', '1-618-516-0417 x5478', 'Eastvale, NY', 12, '["Fleet Management","SAP ERP","Supply Chain Optimization","ISO 14001 Compliance","OSHA Safety Protocols"]', 'Rotational', 'B.S. Environmental Science, MIT', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/73.jpg', 'Celebrer patruus ancilla communis.'),
(34, 'Chad Turner', 'Chad_Turner60@yahoo.com', '465-594-2426 x126', 'Dickinsonville, NM', 7, '["Inventory Control","Plastic Extrusion","Scrap Metal Grading","SAP ERP","ISO 14001 Compliance"]', 'Day Shift', 'B.S. Environmental Science, Purdue University', 'https://avatars.githubusercontent.com/u/8311400', 'Agnosco numquam centum decretum voluptatibus antea delicate.'),
(35, 'Paula Ledner', 'Paula.Ledner@gmail.com', '(440) 713-5672', 'Seattle, NM', 5, '["Supply Chain Optimization","Wastewater Treatment","ISO 14001 Compliance"]', 'Flexible', 'B.S. Environmental Science, Purdue University', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/76.jpg', 'Tubineus comitatus vestigium adopto.'),
(36, 'Dora Deckow', 'Dora_Deckow@yahoo.com', '318.740.2769 x740', 'Midland, IN', 19, '["OSHA Safety Protocols","SAP ERP","Plastic Extrusion"]', 'Rotational', 'B.S. Environmental Science, Stanford', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/12.jpg', 'Perferendis assumenda quo expedita.'),
(37, 'Kari Labadie', 'Kari_Labadie@hotmail.com', '(931) 765-1803 x8464', 'Lake Gailhaven, OH', 6, '["Plastic Extrusion","Fleet Management","Hazardous Waste Management","Wastewater Treatment"]', 'Day Shift', 'B.S. Environmental Science, Local State Tech', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/16.jpg', 'Crudelis depereo adflicto reprehenderit.'),
(38, 'Ira Reinger', 'Ira.Reinger77@gmail.com', '1-573-796-1869 x85702', 'Donnyworth, NC', 16, '["Fleet Management","Plastic Extrusion","Lean Six Sigma","Inventory Control"]', 'Day Shift', 'B.S. Environmental Science, MIT', 'https://avatars.githubusercontent.com/u/12826330', 'Caput uberrime averto subvenio.'),
(39, 'Florence Bartoletti', 'Florence_Bartoletti@yahoo.com', '281.856.5463 x667', 'Tremainefort, WI', 19, '["Wastewater Treatment","SAP ERP","Supply Chain Optimization","Plastic Extrusion","Lean Six Sigma"]', 'Rotational', 'B.S. Environmental Science, MIT', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/24.jpg', 'Cursim depereo animus tamisium comes.'),
(40, 'Gene Cummings', 'Gene.Cummings@hotmail.com', '1-377-968-9641 x1833', 'Lake Brandtworth, IN', 5, '["Circular Economy Principles","Scrap Metal Grading","Plastic Extrusion","Lean Six Sigma"]', 'Night Shift', 'B.S. Environmental Science, Georgia Tech', 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/79.jpg', 'Viridis teres cimentarius.');

INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES
(1, 95.6, 94.5, 86.8),
(2, 91.7, 95.7, 74),
(3, 90.7, 71.9, 80.6),
(4, 76, 81.7, 91.1),
(5, 80.6, 69.2, 92.7),
(6, 75.8, 85.6, 73.2),
(7, 88.6, 79.2, 82.7),
(8, 92.5, 66.2, 85.9),
(9, 89.5, 69.4, 82.7),
(10, 76.6, 75.4, 87.4),
(11, 68.4, 65.4, 70.4),
(12, 95, 64.9, 71),
(13, 76.4, 77.9, 89.8),
(14, 76.8, 78.2, 90.2),
(15, 76, 88.8, 72.3),
(16, 91.8, 70.4, 90.9),
(17, 90.7, 77.4, 90.2),
(18, 69.3, 83.6, 72.5),
(19, 86.3, 91.8, 89.4),
(20, 75.5, 63.5, 77.6),
(21, 77, 82.5, 78.7),
(22, 74.5, 76.7, 80.8),
(23, 92.4, 79.1, 77.5),
(24, 89, 86.5, 90.2),
(25, 81.7, 77.7, 73.2),
(26, 92.5, 82, 82.7),
(27, 70.7, 71.5, 70.9),
(28, 77.7, 72.9, 91.4),
(29, 71.6, 84, 90.1),
(30, 86.3, 85, 74.5),
(31, 68.9, 87.8, 78.5),
(32, 96.8, 83.6, 80.2),
(33, 92, 74, 93.2),
(34, 68, 90.5, 78.8),
(35, 76.9, 83.5, 83.2),
(36, 89.6, 89.8, 91.6),
(37, 93.3, 60.1, 74.8),
(38, 82.6, 95.2, 86.2),
(39, 71.2, 85.1, 79.4),
(40, 74.8, 66.1, 77);
